#!/bin/sh
clear
sudo pacman -S git

git clone https://aur.archlinux.org/yay-bin
cd;cd yay-bin
makepkg -si
cd
yay -S rnote win11-clipboard-history-bin figlet lolcat unzip wget kitty zsh fastfetch discord cmatrix-git asciiquarium-transparent-git cava flatpak btop vim zen-browser-bin pipes.sh tty-clock vscodium-bin libreoffice-fresh pokeshell ttf-jetbrains-mono-nerd eog reflector zsh-autosuggestions zsh-syntax-highlighting obsidian gnome-characters obsidian obs-studio nwg-look ttf-ms-fonts otf-san-francisco audacity kdenlive localsend-bin qt6ct
clear
flatpak install sober
clear
figlet -c ethaninstall is done! | lolcat -a -s 90 -p 2

pkill kitty
pkill ghostty
pkill wezterm
pkill konsole
pkill wezterm
pkill cosmic-terminal
pkill alacritty
pkill warp

