#!/bin/sh

clear

echo  "ethaninstall's git should download in 3 seconds"

sleep 3

sudo pacman -S git go

cd 

git clone https://aur.archlinux.org/yay
cd yay
makepkg -si

yay -S figlet lolcat unzip wget ghostty zsh fastfetch discord cmatrix-git asciiquarium-transparent-git cava spotify flatpak btop vim zen-browser-bin pipes.sh tty-clock vscodium-bin libreoffice-fresh ttf-jetbrains-mono-nerd mpv eog cheese reflector zsh-autosuggestions zsh-syntax-highlighting obsidian bibata-cursor-theme-bin papirus-icon-theme gnome-characters gnome-calculator gnome-calendar obsidian

sleep 1

clear

flatpak install sober

clear

figlet ethaninstall is done! | lolcat -a -s 200
